### ISSUE TITLE
Проект еще жив?

### ISSUE THREAD

**Issue by netman1ac** [lanket/mdmPiTerminalModule#6]
Тут появился еще один проект https://github.com/Aculeasis/mdmTerminal2
Можно под него модуль доделать? 
несовместимые настройки вынести в отдельное меню или просто подписать что они для V2

**Comment by lanket** [comment]
@netman1ac посмотрю, но времени сейчас совсем нет. Постараюсь не затягивать.

**Comment by Aculeasis** [comment]
Если всех то https://github.com/Aculeasis/mdmTerminal2/wiki/settings.ini
