### ISSUE TITLE
Описание параметров mdmTerminal2

### ISSUE THREAD

**Issue by netman1ac** [lanket/mdmPiTerminalModule#7]
Все параметры тут:
https://github.com/Aculeasis/mdmTerminal2/wiki/settings.ini
Надо еще будет обсудить с автором что выносить в модуль, а что лучше руками в конфиге
ибо можно так настроить что работать не будет 
Ну и стоит написать что эти параметры работают в V1(mdmPiTerminal) и в V2, а эти только в V2 (mdmTerminal2)

**Comment by Aculeasis** [comment]
Наверное проще 2 вкладки сделать, там же провайдеров больше.

Параметры для других секций лучше всего присылать во вложенных json, например:
```
settings:{"proxy": {"enable": "1"}}
```
Они нормально парсятся. Терминал принимает любые параметры, но не принимает несуществующие секции.
Установку `server` для локальных провайдеров можно через ключи сделать.

**Comment by Aculeasis** [comment]
Еще можно отправлять `{"majordomo": {"terminal": "sysname"}}`, как я понял если в запросе задано системное имя терминала то и ответ придет на тот же терминал.
https://github.com/sergejey/majordomo-chromegate/blob/master/js/main.js#L196

**Comment by lanket** [comment]
> 
> 
> Все параметры тут:
> https://github.com/Aculeasis/mdmTerminal2/wiki/settings.ini
> Надо еще будет обсудить с автором что выносить в модуль, а что лучше руками в конфиге
> ибо можно так настроить что работать не будет
> Ну и стоит написать что эти параметры работают в V1(mdmPiTerminal) и в V2, а эти только в V2 (mdmTerminal2)

Так можно сюда либо для оперативности в телегу

**Comment by lanket** [comment]
> 
> 
> Наверное проще 2 вкладки сделать, там же провайдеров больше.
Видать придется со вкладками, уж очень много настроек.
> Параметры для других секций лучше всего присылать во вложенных json, например:
> 
> ```
> settings:{"proxy": {"enable": "1"}}
> ```
Не понял для чего, скрипту побарабану на читабельность.
На сколько это нужно?

> Они нормально парсятся. Терминал принимает любые параметры, но не принимает несуществующие секции.
> Установку `server` для локальных провайдеров можно через ключи сделать.
??? каких провайдеров???

**Comment by lanket** [comment]
> 
> 
> Еще можно отправлять `{"majordomo": {"terminal": "sysname"}}`, как я понял если в запросе задано системное имя терминала то и ответ придет на тот же терминал.
> https://github.com/sergejey/majordomo-chromegate/blob/master/js/main.js#L196

Так это к модулю не имеет отношения, это уже на уровне системы отрабатываеся

**Comment by Aculeasis** [comment]
> На сколько это нужно?

Нельзя будет обработать две одинаковые настройки если они в разных разделах.

> каких провайдеров???

tts rhvoice-rest, stt pocketsphinx-rest

> Так это к модулю не имеет отношения, это уже на уровне системы отрабатываеся

Ну система не присылает название терминала, а задать его можно (хз зачем правда, 2 терминала на одном ип?)

**Comment by lanket** [comment]
Описания очень большие, lang_check не нужно давблять это для отладки. lang я бы тоже не стал добавлять, там только русский и есть.
token лучше убрать, кому надо сами добавят. tts yandex нет, но его первая версия не поймет.
А нельзя сделать короткие описания во сплывающими подсказками?
Dar Adal
optimistic_nonblock_tts лучше тоже убрать

**Comment by lanket** [comment]
Alexandr:
Добавь плиз поле для ввода чувствительности ручками. У меня система сходит с ума на 0.4 и ничего не слышит на 3.5 
Нормально работает  на 3.7-3.8

**Comment by lanket** [comment]
no_hello = 0
ask_me_again = 1
alarmkwactivated = 1
providerstt = google
providertts = yandex
alarmstt = 1
sensitivity = 0.38
alarmtts = 1
quiet = 1
phrase_time_limit = 10
возможно еще это бы 
[snowboy]
token
[yandex]
apikeytts = 
speaker = alyss
emotion = good
остальное скорей всего надо только опытным

**Comment by Aculeasis** [comment]
Может еще добавить кнопки для удаления моделей и перезаписи settings.ini? Например `rec:del:`, `rec:dump`.

**Comment by netman1ac** [comment]
Может хром мод еще?
chrome_mode = 1
chrome_choke = 0
chrome_alarmstt = 0

Я его правда так и не тестил

**Comment by lanket** [comment]
> 
> 
> Может еще добавить кнопки для удаления моделей и перезаписи settings.ini? Например `rec:del:`, `rec:dump`.

Хорошо.

**Comment by lanket** [comment]
> 
> 
> Может хром мод еще?
> chrome_mode = 1
> chrome_choke = 0
> chrome_alarmstt = 0
> 
> Я его правда так и не тестил

Это чтобы ключевое в контексте предложения было? 
Без ожидания подтверждения что среагировал на ключевое?
Если так то обязательно надо!!!

**Comment by Aculeasis** [comment]
> Это чтобы ключевое в контексте предложения было?

Да, я включил его по умолчанию. Иначе много ложных срабатываний с колонками (или у меня микрофон настолько плохой).

> Хорошо.

Вообще `rec:dump` не нужно, добавил версионирование конфига для автообновления параметров.

**Comment by Aculeasis** [comment]
Добавить систему автообновлений https://github.com/Aculeasis/mdmTerminal2/commit/da81061cea5915061eaf79ae22b351abdafc32cf

Можно добавить кнопки:
- Обновить терминал - `rec:update_0_0`
- Откатить термина до предыдущего успешного обновления - `rec:rollback_0_0`

**Comment by lanket** [comment]
> 
> 
> Может еще добавить кнопки для удаления моделей и перезаписи settings.ini? Например `rec:del:`, `rec:dump`.

Удалить модель добавил, а вот перезапись не понял зачем. при отправки настроек в терминал и так сетинс.ини перезаписывается. надо ли?

**Comment by Aculeasis** [comment]
> Удалить модель добавил, а вот перезапись не понял зачем. при отправки настроек в терминал и так сетинс.ини перезаписывается. надо ли?

Не надо.

**Comment by lanket** [comment]
Идем дальше
